### ISSUE TITLE
MFCC block does not build out of the box

### ISSUE THREAD

**Issue by ijdoc** [edgeimpulse/processing-blocks#12]
Error is:

``` sh
$ docker build .
[+] Building 180.7s (10/12)
 => [internal] load build definition from Dockerfile                                                                                                                                                                     0.0s
 => => transferring dockerfile: 316B                                                                                                                                                                                     0.0s
 => [internal] load .dockerignore                                                                                                                                                                                        0.0s
 => => transferring context: 2B                                                                                                                                                                                          0.0s
 => resolve image config for docker.io/docker/dockerfile:experimental                                                                                                                                                    1.2s
 => CACHED docker-image://docker.io/docker/dockerfile:experimental@sha256:600e5c62eedff338b3f7a0850beb7c05866e0ef27b2d2e8c02aa468e78496ff5                                                                               0.0s
 => [internal] load metadata for docker.io/library/python:3.9.7                                                                                                                                                          0.4s
 => [1/6] FROM docker.io/library/python:3.9.7@sha256:8771691756bbf5beff80d64fca8f5b12e018352ddd9e30d8cdfef8cc3717b0e6                                                                                                    0.0s
 => [internal] load build context                                                                                                                                                                                        0.0s
 => => transferring context: 43.90kB                                                                                                                                                                                     0.0s
 => CACHED [2/6] WORKDIR /app                                                                                                                                                                                            0.0s
 => [3/6] COPY requirements-blocks.txt ./                                                                                                                                                                                0.0s
 => ERROR [4/6] RUN pip3 --no-cache-dir install -r requirements-blocks.txt                                                                                                                                             178.8s
------
 > [4/6] RUN pip3 --no-cache-dir install -r requirements-blocks.txt:
#10 1.604 Collecting audioread==2.1.9
#10 1.716   Downloading audioread-2.1.9.tar.gz (377 kB)
#10 2.228 Collecting librosa==0.8.0
#10 2.248   Downloading librosa-0.8.0.tar.gz (183 kB)
#10 2.796 Collecting matplotlib==3.1.0
#10 2.819   Downloading matplotlib-3.1.0.tar.gz (37.2 MB)
#10 22.44 Collecting numpy==1.17.5
#10 22.46   Downloading numpy-1.17.5.zip (6.4 MB)
#10 24.91 Collecting PeakUtils==1.3.2
#10 24.93   Downloading PeakUtils-1.3.2.tar.gz (31 kB)
#10 25.70 Collecting Pillow==7.1.2
#10 25.71   Downloading Pillow-7.1.2.tar.gz (38.9 MB)
#10 37.61 Collecting requests==2.22.0
#10 37.64   Downloading requests-2.22.0-py2.py3-none-any.whl (57 kB)
#10 37.69 Collecting requests-oauthlib==1.3.0
#10 37.71   Downloading requests_oauthlib-1.3.0-py2.py3-none-any.whl (23 kB)
#10 37.74 Collecting requests-unixsocket==0.2.0
#10 37.76   Downloading requests_unixsocket-0.2.0-py2.py3-none-any.whl (11 kB)
#10 38.03 Collecting scikit-learn==0.21.2
#10 38.05   Downloading scikit-learn-0.21.2.tar.gz (12.2 MB)
#10 42.55 Collecting scipy==1.4.1
#10 42.57   Downloading scipy-1.4.1.tar.gz (24.6 MB)
#10 50.86   Installing build dependencies: started
#10 126.5   Installing build dependencies: still running...
#10 177.2   Installing build dependencies: finished with status 'done'
#10 177.2   Getting requirements to build wheel: started
#10 177.5   Getting requirements to build wheel: finished with status 'done'
#10 177.5     Preparing wheel metadata: started
#10 178.0     Preparing wheel metadata: finished with status 'error'
#10 178.0     ERROR: Command errored out with exit status 1:
#10 178.0      command: /usr/local/bin/python /usr/local/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_wheel /tmp/tmppi4fs_wz
#10 178.0          cwd: /tmp/pip-install-1qyz__e3/scipy_b58949c37058470788a5e142bc8f2716
#10 178.0     Complete output (139 lines):
#10 178.0     setup.py:418: UserWarning: Unrecognized setuptools command ('dist_info --egg-base /tmp/pip-modern-metadata-dcorq6m5'), proceeding with generating Cython sources and expanding templates
#10 178.0       warnings.warn("Unrecognized setuptools command ('{}'), proceeding with "
#10 178.0     Running from scipy source directory.
#10 178.0     lapack_opt_info:
#10 178.0     lapack_mkl_info:
#10 178.0     customize UnixCCompiler
#10 178.0       libraries mkl_rt not found in ['/usr/local/lib', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
#10 178.0       NOT AVAILABLE
#10 178.0
#10 178.0     openblas_lapack_info:
#10 178.0     customize UnixCCompiler
#10 178.0     customize UnixCCompiler
#10 178.0       libraries openblas not found in ['/usr/local/lib', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
#10 178.0       NOT AVAILABLE
#10 178.0
#10 178.0     openblas_clapack_info:
#10 178.0     customize UnixCCompiler
#10 178.0     customize UnixCCompiler
#10 178.0       libraries openblas,lapack not found in ['/usr/local/lib', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
#10 178.0       NOT AVAILABLE
#10 178.0
#10 178.0     flame_info:
#10 178.0     customize UnixCCompiler
#10 178.0       libraries flame not found in ['/usr/local/lib', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
#10 178.0       NOT AVAILABLE
#10 178.0
#10 178.0     atlas_3_10_threads_info:
#10 178.0     Setting PTATLAS=ATLAS
#10 178.0     customize UnixCCompiler
#10 178.0       libraries lapack_atlas not found in /usr/local/lib
#10 178.0     customize UnixCCompiler
#10 178.0       libraries tatlas,tatlas not found in /usr/local/lib
#10 178.0     customize UnixCCompiler
#10 178.0       libraries lapack_atlas not found in /usr/lib
#10 178.0     customize UnixCCompiler
#10 178.0       libraries tatlas,tatlas not found in /usr/lib
#10 178.0     customize UnixCCompiler
#10 178.0       libraries lapack_atlas not found in /usr/lib/x86_64-linux-gnu
#10 178.0     customize UnixCCompiler
#10 178.0       libraries tatlas,tatlas not found in /usr/lib/x86_64-linux-gnu
#10 178.0     <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
#10 178.0       NOT AVAILABLE
#10 178.0
#10 178.0     atlas_3_10_info:
#10 178.0     customize UnixCCompiler
#10 178.0       libraries lapack_atlas not found in /usr/local/lib
#10 178.0     customize UnixCCompiler
#10 178.0       libraries satlas,satlas not found in /usr/local/lib
#10 178.0     customize UnixCCompiler
#10 178.0       libraries lapack_atlas not found in /usr/lib
#10 178.0     customize UnixCCompiler
#10 178.0       libraries satlas,satlas not found in /usr/lib
#10 178.0     customize UnixCCompiler
#10 178.0       libraries lapack_atlas not found in /usr/lib/x86_64-linux-gnu
#10 178.0     customize UnixCCompiler
#10 178.0       libraries satlas,satlas not found in /usr/lib/x86_64-linux-gnu
#10 178.0     <class 'numpy.distutils.system_info.atlas_3_10_info'>
#10 178.0       NOT AVAILABLE
#10 178.0
#10 178.0     atlas_threads_info:
#10 178.0     Setting PTATLAS=ATLAS
#10 178.0     customize UnixCCompiler
#10 178.0       libraries lapack_atlas not found in /usr/local/lib
#10 178.0     customize UnixCCompiler
#10 178.0       libraries ptf77blas,ptcblas,atlas not found in /usr/local/lib
#10 178.0     customize UnixCCompiler
#10 178.0       libraries lapack_atlas not found in /usr/lib
#10 178.0     customize UnixCCompiler
#10 178.0       libraries ptf77blas,ptcblas,atlas not found in /usr/lib
#10 178.0     customize UnixCCompiler
#10 178.0       libraries lapack_atlas not found in /usr/lib/x86_64-linux-gnu
#10 178.0     customize UnixCCompiler
#10 178.0       libraries ptf77blas,ptcblas,atlas not found in /usr/lib/x86_64-linux-gnu
#10 178.0     <class 'numpy.distutils.system_info.atlas_threads_info'>
#10 178.0       NOT AVAILABLE
#10 178.0
#10 178.0     atlas_info:
#10 178.0     customize UnixCCompiler
#10 178.0       libraries lapack_atlas not found in /usr/local/lib
#10 178.0     customize UnixCCompiler
#10 178.0       libraries f77blas,cblas,atlas not found in /usr/local/lib
#10 178.0     customize UnixCCompiler
#10 178.0       libraries lapack_atlas not found in /usr/lib
#10 178.0     customize UnixCCompiler
#10 178.0       libraries f77blas,cblas,atlas not found in /usr/lib
#10 178.0     customize UnixCCompiler
#10 178.0       libraries lapack_atlas not found in /usr/lib/x86_64-linux-gnu
#10 178.0     customize UnixCCompiler
#10 178.0       libraries f77blas,cblas,atlas not found in /usr/lib/x86_64-linux-gnu
#10 178.0     <class 'numpy.distutils.system_info.atlas_info'>
#10 178.0       NOT AVAILABLE
#10 178.0
#10 178.0     accelerate_info:
#10 178.0       NOT AVAILABLE
#10 178.0
#10 178.0     lapack_info:
#10 178.0     customize UnixCCompiler
#10 178.0       libraries lapack not found in ['/usr/local/lib', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
#10 178.0       NOT AVAILABLE
#10 178.0
#10 178.0     /tmp/pip-build-env-sgo_b9zk/overlay/lib/python3.9/site-packages/numpy/distutils/system_info.py:1712: UserWarning:
#10 178.0         Lapack (http://www.netlib.org/lapack/) libraries not found.
#10 178.0         Directories to search for the libraries can be specified in the
#10 178.0         numpy/distutils/site.cfg file (section [lapack]) or by setting
#10 178.0         the LAPACK environment variable.
#10 178.0       if getattr(self, '_calc_info_{}'.format(lapack))():
#10 178.0     lapack_src_info:
#10 178.0       NOT AVAILABLE
#10 178.0
#10 178.0     /tmp/pip-build-env-sgo_b9zk/overlay/lib/python3.9/site-packages/numpy/distutils/system_info.py:1712: UserWarning:
#10 178.0         Lapack (http://www.netlib.org/lapack/) sources not found.
#10 178.0         Directories to search for the sources can be specified in the
#10 178.0         numpy/distutils/site.cfg file (section [lapack_src]) or by setting
#10 178.0         the LAPACK_SRC environment variable.
#10 178.0       if getattr(self, '_calc_info_{}'.format(lapack))():
#10 178.0       NOT AVAILABLE
#10 178.0
#10 178.0     Traceback (most recent call last):
#10 178.0       File "/usr/local/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 349, in <module>
#10 178.0         main()
#10 178.0       File "/usr/local/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 331, in main
#10 178.0         json_out['return_val'] = hook(**hook_input['kwargs'])
#10 178.0       File "/usr/local/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 151, in prepare_metadata_for_build_wheel
#10 178.0         return hook(metadata_directory, config_settings)
#10 178.0       File "/tmp/pip-build-env-sgo_b9zk/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 188, in prepare_metadata_for_build_wheel
#10 178.0         self.run_setup()
#10 178.0       File "/tmp/pip-build-env-sgo_b9zk/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 281, in run_setup
#10 178.0         super(_BuildMetaLegacyBackend,
#10 178.0       File "/tmp/pip-build-env-sgo_b9zk/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 174, in run_setup
#10 178.0         exec(compile(code, __file__, 'exec'), locals())
#10 178.0       File "setup.py", line 540, in <module>
#10 178.0         setup_package()
#10 178.0       File "setup.py", line 536, in setup_package
#10 178.0         setup(**metadata)
#10 178.0       File "/tmp/pip-build-env-sgo_b9zk/overlay/lib/python3.9/site-packages/numpy/distutils/core.py", line 137, in setup
#10 178.0         config = configuration()
#10 178.0       File "setup.py", line 435, in configuration
#10 178.0         raise NotFoundError(msg)
#10 178.0     numpy.distutils.system_info.NotFoundError: No lapack/blas resources found.
#10 178.0     ----------------------------------------
#10 178.0 WARNING: Discarding https://files.pythonhosted.org/packages/04/ab/e2eb3e3f90b9363040a3d885ccc5c79fe20c5b8a3caa8fe3bf47ff653260/scipy-1.4.1.tar.gz#sha256=dee1bbf3a6c8f73b6b218cb28eed8dd13347ea2f87d572ce19b289d6fd3fbc59 (from https://pypi.org/simple/scipy/) (requires-python:>=3.5). Command errored out with exit status 1: /usr/local/bin/python /usr/local/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_wheel /tmp/tmppi4fs_wz Check the logs for full command output.
#10 178.0 ERROR: Could not find a version that satisfies the requirement scipy==1.4.1 (from versions: 0.8.0, 0.9.0, 0.10.0, 0.10.1, 0.11.0, 0.12.0, 0.12.1, 0.13.0, 0.13.1, 0.13.2, 0.13.3, 0.14.0, 0.14.1, 0.15.0, 0.15.1, 0.16.0, 0.16.1, 0.17.0, 0.17.1, 0.18.0, 0.18.1, 0.19.0, 0.19.1, 1.0.0b1, 1.0.0rc1, 1.0.0rc2, 1.0.0, 1.0.1, 1.1.0rc1, 1.1.0, 1.2.0rc1, 1.2.0rc2, 1.2.0, 1.2.1, 1.2.2, 1.2.3, 1.3.0rc1, 1.3.0rc2, 1.3.0, 1.3.1, 1.3.2, 1.3.3, 1.4.0rc1, 1.4.0rc2, 1.4.0, 1.4.1, 1.5.0rc1, 1.5.0rc2, 1.5.0, 1.5.1, 1.5.2, 1.5.3, 1.5.4, 1.6.0rc1, 1.6.0rc2, 1.6.0, 1.6.1, 1.6.2, 1.6.3, 1.7.0rc1, 1.7.0rc2, 1.7.0, 1.7.1, 1.7.2, 1.7.3, 1.8.0rc1, 1.8.0rc2, 1.8.0rc3, 1.8.0rc4, 1.8.0)
#10 178.0 ERROR: No matching distribution found for scipy==1.4.1
#10 178.1 WARNING: You are using pip version 21.2.4; however, version 22.0.3 is available.
#10 178.1 You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
------
executor failed running [/bin/sh -c pip3 --no-cache-dir install -r requirements-blocks.txt]: exit code: 1
```

**Comment by janjongboom** [comment]
I've seen this in other contexts and just following https://askubuntu.com/questions/623578/installing-blas-and-lapack-packages (exact command tbd) typically works.
